version: "3.10.8"
services:
  worker:
    build: .
    environment:
      BOT_TOKEN: $BOT_TOKEN
      API_ID: $API_ID
      API_HASH: $API_HASH
      CHANNELS: $CHANNELS
      ADMINS: $ADMINS
      PICS: $PICS
      LOG_CHANNEL: $LOG_CHANNEL
      AUTH_USERS: $AUTH_USERS
      AUTH_CHANNEL: $AUTH_CHANNEL
      DATABASE_URI: $DATABASE_URI
      DATABASE_NAME: $DATABASE_NAME
      COLLECTION_NAME: $COLLECTION_NAME
      HEROKU_API_KEY: $HEROKU_API_KEY
